<%@ Page Title="" Language="C#" MasterPageFile="~/Student.Master" AutoEventWireup="true" CodeBehind="StudentBookings.aspx.cs" Inherits="Synergince.StudentBookings" %>
<asp:Content ID="Content1" ContentPlaceHolderID="head" runat="server">
    <link href="StyleSheet2.css" rel="stylesheet" type="text/css" />
<div id="site-content">
			<header class="site-header">
				
					<a href="StudentHome.aspx" id="branding">
						<img src= "Image/images.png" alt="Site Title" />
                       <%-- &nbsp;--%>
					</a> <!-- #branding -->
					
					<nav class="main-navigation">
						<button type="button" class="toggle-menu"><i class="fa fa-bars"></i></button>
						<ul class="menu">
							<li class="menu-item"><a href="StudentHome.aspx">Home</a></li>
							<li class="menu-item"><a href="StudentProfile.aspx">My Profile</a></li>
							<li class="menu-item"><a href="StudentBookSI.aspx">Book SI</a></li>
							<li class="menu-item"><a href="StudentBookLWAP.aspx">Book LWAP</a></li>
							<li class="menu-item current-menu-item"><a href="StudentBookings.aspx">My Bookings</a></li>
							<li class="menu-item"><a href="Account/Login.aspx">Logout</a></li>
						</ul> <!-- .menu -->
					</nav> <!-- .main-navigation -->
					<div class="mobile-menu"></div>
        </div>
       
    <style type="text/css">
        .style1
        {
            width: 100%;
        }
        .style2
        {
            width: 70px;
        }
    </style>
    <style type="text/css">
        .style1
        {
            width: 17px;
        }
        .style2
        {
            width: 21px;
        }
        .style3
        {
            width: 48px;
        }
        .style4
        {
            width: 446px;
        }
    </style>
    <style type="text/css">
        .style1
        {
            width: 779px;
        }
        .style2
        {
            width: 806px;
        }
        .style5
        {
            width: 806px;
            height: 58px;
            font-weight: bold;
        }
        .style6
        {
            width: 705px;
            height: 58px;
        }
        .style7
        {
            height: 58px;
            width: 679px;
        }
        .style8
        {
            width: 806px;
            height: 65px;
        }
        .style10
        {
            height: 65px;
            width: 679px;
        }
        .style11
        {
            width: 806px;
            height: 398px;
        }
        .style13
        {
            height: 398px;
            width: 679px;
        }
        .style14
        {
            width: 806px;
            font-weight: bold;
        }
        .style15
        {
            width: 705px;
        }
        .style16
        {
            width: 705px;
            height: 398px;
        }
        .style17
        {
            width: 705px;
            height: 65px;
        }
        .style18
        {
            width: 679px;
        }
    </style>
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="ContentPlaceHolder1" runat="server">
    <table class="style1">
        <tr>
            <td class="style14">
                &nbsp;</td>
            <td class="style15">
                &nbsp;</td>
            <td class="style18">
                &nbsp;</td>
        </tr>
        <tr>
            <td class="style5">
                Select:</td>
            <td class="style6">
                <asp:LinkButton ID="lbtnSI" runat="server" onclick="lbtnSI_Click">SI Bookings</asp:LinkButton>
            </td>
            <td class="style7">
                <asp:LinkButton ID="lbtnLWAP" runat="server" onclick="lbtnLWAP_Click">LWAP Bookings</asp:LinkButton>
            </td>
        </tr>
        <tr>
            <td class="style2">
                &nbsp;</td>
            <td class="style15">
                <asp:SqlDataSource ID="SqlDataSource1" runat="server" 
                    ConnectionString="<%$ ConnectionStrings:tlcString %>" 
                    SelectCommand="SELECT [BookingID], [StudentNumber], [Date], [Time], [Course], [SIName], [Description] FROM [Bookings]">
                </asp:SqlDataSource>
            </td>
            <td class="style18">
                <asp:SqlDataSource ID="SqlDataSource2" runat="server" 
                    ConnectionString="<%$ ConnectionStrings:tlcString %>" 
                    SelectCommand="SELECT [BookingID], [StudentNumber], [Date], [Time], [LWAPName], [Document] FROM [Bookings]">
                </asp:SqlDataSource>
            </td>
        </tr>
        <tr>
            <td class="style11">
                </td>
            <td class="style16">
                <asp:GridView ID="grdSIBook" runat="server" AllowPaging="True" 
                    AllowSorting="True" AutoGenerateColumns="False" AutoGenerateDeleteButton="True" 
                    AutoGenerateEditButton="True" CellPadding="4" DataKeyNames="BookingID" 
                    DataSourceID="SqlDataSource1" ForeColor="#333333" GridLines="None" 
                    Visible="False" Width="700px">
                    <AlternatingRowStyle BackColor="White" />
                    <Columns>
                        <asp:CommandField ShowSelectButton="True" />
                        <asp:BoundField DataField="BookingID" HeaderText="BookingID" 
                            InsertVisible="False" ReadOnly="True" SortExpression="BookingID" />
                        <asp:BoundField DataField="StudentNumber" HeaderText="StudentNumber" 
                            SortExpression="StudentNumber" />
                        <asp:BoundField DataField="Date" HeaderText="Date" SortExpression="Date" />
                        <asp:BoundField DataField="Time" HeaderText="Time" SortExpression="Time" />
                        <asp:BoundField DataField="Course" HeaderText="Course" 
                            SortExpression="Course" />
                        <asp:BoundField DataField="SIName" HeaderText="SIName" 
                            SortExpression="SIName" />
                        <asp:BoundField DataField="Description" HeaderText="Description" 
                            SortExpression="Description" />
                    </Columns>
                    <EditRowStyle BackColor="#2461BF" />
                    <EmptyDataTemplate>
                        No bookings found.
                    </EmptyDataTemplate>
                    <FooterStyle BackColor="#507CD1" Font-Bold="True" ForeColor="White" />
                    <HeaderStyle BackColor="#507CD1" Font-Bold="True" ForeColor="White" />
                    <PagerStyle BackColor="#2461BF" ForeColor="White" HorizontalAlign="Center" />
                    <RowStyle BackColor="#EFF3FB" />
                    <SelectedRowStyle BackColor="#D1DDF1" Font-Bold="True" ForeColor="#333333" />
                    <SortedAscendingCellStyle BackColor="#F5F7FB" />
                    <SortedAscendingHeaderStyle BackColor="#6D95E1" />
                    <SortedDescendingCellStyle BackColor="#E9EBEF" />
                    <SortedDescendingHeaderStyle BackColor="#4870BE" />
                </asp:GridView>
            </td>
            <td class="style13">
                <asp:GridView ID="grdLWAPBook" runat="server" AllowPaging="True" 
                    AllowSorting="True" AutoGenerateColumns="False" AutoGenerateDeleteButton="True" 
                    AutoGenerateEditButton="True" CellPadding="4" DataKeyNames="BookingID" 
                    DataSourceID="SqlDataSource2" ForeColor="#333333" GridLines="None" 
                    Visible="False">
                    <AlternatingRowStyle BackColor="White" />
                    <Columns>
                        <asp:CommandField ShowSelectButton="True" />
                        <asp:BoundField DataField="BookingID" HeaderText="BookingID" 
                            InsertVisible="False" ReadOnly="True" SortExpression="BookingID" />
                        <asp:BoundField DataField="StudentNumber" HeaderText="StudentNumber" 
                            SortExpression="StudentNumber" />
                        <asp:BoundField DataField="Date" HeaderText="Date" SortExpression="Date" />
                        <asp:BoundField DataField="Time" HeaderText="Time" SortExpression="Time" />
                        <asp:BoundField DataField="LWAPName" HeaderText="LWAPName" 
                            SortExpression="LWAPName" />
                    </Columns>
                    <EditRowStyle BackColor="#2461BF" />
                    <EmptyDataTemplate>
                        No bookings found.
                    </EmptyDataTemplate>
                    <FooterStyle BackColor="#507CD1" Font-Bold="True" ForeColor="White" />
                    <HeaderStyle BackColor="#507CD1" Font-Bold="True" ForeColor="White" />
                    <PagerStyle BackColor="#2461BF" ForeColor="White" HorizontalAlign="Center" />
                    <RowStyle BackColor="#EFF3FB" />
                    <SelectedRowStyle BackColor="#D1DDF1" Font-Bold="True" ForeColor="#333333" />
                    <SortedAscendingCellStyle BackColor="#F5F7FB" />
                    <SortedAscendingHeaderStyle BackColor="#6D95E1" />
                    <SortedDescendingCellStyle BackColor="#E9EBEF" />
                    <SortedDescendingHeaderStyle BackColor="#4870BE" />
                </asp:GridView>
            </td>
        </tr>
        <tr>
            <td class="style8">
                </td>
            <td class="style17">
                </td>
            <td class="style10">
                </td>
        </tr>
    </table>
</asp:Content>
